WIP: Modificação nas telas de abrigos para adicionar cidades
SOS-RS/frontend pull request #110
Opened 2024-05-12 07:40 UTC by kelvinsb

## Descrição
Com a criação de diversos campos de endereço e a normalização do campo `city` e melhorar a experiência do site é preciso fazer algumas alterações de filtros baseado em cidade

## Mudanças
- Filtro de cidade
   - Os filtros selecionados de cidades são exibidos embaixo do campo de `Buscar por abrigo ou endereço`
      - Clicando em um este é removido
   - Ao clicar em `Filtros` tem uma nova seção `Qual cidade você quer ajudar?`
      - Em que se pode selecionar várias cidades para o filtro funcionar 
- Formulário de abrigo
   - Criação e edição de abrigo: com campo de pesquisa com cidades já populados do RS 
 - Exibição de cidade
    - Nos abrigos listados na página inicial após o nome do abrigo é exposto a cidade: ` - Cidade` 
    - Na página de detalhes do abrigo também é exposto a cidade

## Rotas novas consultadas
- `shelters/cities`: para consulta das cidades disponíveis e a quantidade de abrigos para cada um

## O que falta
 - [ ] Alinhar com time de UX sobre mudanças

## Depende
- https://github.com/SOS-RS/backend/pull/82

depends on [backend#](https://github.com/SOS-RS/backend/pull/82)

2024-05-13 03:07 UTC, filipepacheco approved these changes
lgtm

2024-05-13 03:17 UTC, AndersonCRocha requested changes

2024-05-13 03:17 UTC, AndersonCRocha commented on src/pages/Home/components/Filter/Filter.tsx
> +          cities: cities,
Dá pra usar shorthand aqui

2024-05-13 03:17 UTC, AndersonCRocha commented on src/pages/Home/components/ShelterListItem/ShelterListItem.tsx
> +          {data.name} - {Boolean(data.city) && <>{data.city}</>}
O tracinho é bom fazer parte do render condicional senão vai acontecer de ficar sobrando um tracinho no final quando não tiver cidade cadastrada

2024-05-13 03:17 UTC, AndersonCRocha commented on src/pages/Home/components/ShelterListView/ShelterListView.tsx
> +                  // onClick={onOpenModal}
O comentário?

2024-05-13 03:17 UTC, AndersonCRocha commented on src/pages/Home/components/ShelterListView/ShelterListView.tsx
> +                          filterData.cities.filter((it) => it !== item)
Ternário não necessário, só usar optional chaining

onCitiesChange?.(........)

2024-05-13 03:17 UTC, AndersonCRocha commented on src/pages/UpdateShelter/UpdateShelter.tsx
> +                  className={`w-full ${
Usar a função utilitária cn() fica mais legível q o ternário aqui

2024-05-13 03:38 UTC, filipefraga commented on src/pages/Home/components/ShelterListItem/ShelterListItem.tsx
> +          {data.name} - {Boolean(data.city) && <>{data.city}</>}
de fato, aqui está com o tracinho
![image](https://github.com/SOS-RS/frontend/assets/139470705/bf96f5fb-c282-4ba0-9d83-86d5f19e8421)

2024-05-13 03:47 UTC, filipefraga commented on src/pages/Home/components/ShelterListItem/ShelterListItem.tsx
> +          {data.name} - {Boolean(data.city) && <>{data.city}</>}
além disso, como os dados de prod ainda não estão normalizados, vai acontecer de aparecer duas vezes a cidade.
eu acho que por enquanto seria melhor deixar comentado essa parte até que o banco esteja normalizado

![image](https://github.com/SOS-RS/frontend/assets/139470705/b2914797-4a02-4f66-ad00-3e994340e0bf)

2024-05-13 17:30 UTC, kelvinsb commented on src/components/CardAboutShelter/CardAboutShelter.tsx
> +  return fields.join(', ');
É uma boa, não sabia fazer dessa maneira, obrigado!

2024-05-13 17:36 UTC, kelvinsb commented on src/pages/Home/components/ShelterListItem/ShelterListItem.tsx
> +          {data.name} - {Boolean(data.city) && <>{data.city}</>}
As 2 recomendações foram boas
Retirei do lado do título e coloquei junto com a formatação do endereço(que não tinha feito mas apliquei no último commit bd62211), pra no momento que não está normalizado:
- Não ficar no título, antes ou depois
- Quando normalizar e remover o endereço já vir formatado nele
   - Talvez seja interessante deixar a cidade com um badge pra facilitar a visualização no futuro 
- Campo de cep CEP na página de detalhes, e a mesma formatação:
![image](https://github.com/SOS-RS/frontend/assets/22968607/a18dc062-1b03-481e-88d2-f794e4d7e798)

2024-05-15 02:18 UTC, MatheusDubin approved these changes

2024-05-15 02:21 UTC, merged