[FEAT] - Create Dashboard page
SOS-RS/frontend pull request #218
Opened 2024-05-17 00:56 UTC by mateusfnogueira

2024-05-21 13:11 UTC, rafael-alves-cs commented on src/components/BurgerMenu/BurgerMenu.tsx
> +            link="/dashboar"
```suggestion
            link="/dashboard"
```

2024-05-21 13:12 UTC, rafael-alves-cs commented on src/hooks/useDashboard/useDashboard.tsx
> +          }
O mesmo código é executado independente da condição

2024-05-21 13:13 UTC, rafael-alves-cs commented on src/hooks/useDashboard/useDashboard.tsx
> +          if (!append) setLoading(false);
```suggestion
          setLoading(!append);
```

2024-05-22 17:15 UTC, mateusfnogueira commented on src/pages/Dashboard/Dashboard.tsx
> +              onClick={() => refresh()}
![image](https://github.com/SOS-RS/frontend/assets/50973708/80f3ad96-1874-42b7-989a-8c238d2c8ce8)
devido a esse erro essa função não pode ser auto invocavel

2024-06-06 15:20 UTC, larissapissurno requested changes
primeiramente, ótimo trabalho @mateusfnogueira 🙌 🚀 

 tentei rodar seu código localmente e encontrei alguns erros ao rodar `npm run build` e `npm run lint`, poderia dar uma olhada neles? obrigada!

fora isso tem também mais um conflito a ser resolvido

2024-06-06 17:43 UTC, mateusfnogueira commented
> primeiramente, ótimo trabalho @mateusfnogueira 🙌 🚀
> 
> tentei rodar seu código localmente e encontrei alguns erros ao rodar `npm run build` e `npm run lint`, poderia dar uma olhada neles? obrigada!
> 
> fora isso tem também mais um conflito a ser resolvido

Opa eu rodei aqui o lint, vou corrigir os erros, mas acredito que esses erros estão em prod também, pois os arquivos que contém os erros já estavam no projeto 

![image](https://github.com/SOS-RS/frontend/assets/50973708/b25163fe-ef44-47b4-bad0-70e96a4493be)

2024-06-08 01:39 UTC, larissapissurno approved these changes
lgtm

2024-06-14 14:48 UTC, merged