Adjust viewport height for mobile devices on Update Shelter page
SOS-RS/frontend pull request #232
Opened 2024-05-17 14:02 UTC by felipemrvieira

[ISSUE 225](https://github.com/SOS-RS/frontend/issues/225)

2024-05-17 15:24 UTC, lucianomlima reviewed
Coloca uns prints mostrando que resolveu e principalmente que não impactou outras resoluções.

2024-05-17 16:19 UTC, felipemrvieira commented
![192 168 0 12_5173_abrigo_3a5e8ab5-5c48-48f3-98f1-f7c9c5b26ddb_atualizar(Pixel 7)](https://github.com/SOS-RS/frontend/assets/13780312/9cffbb0d-43e4-480b-8157-71302c5d82f7)
![192 168 0 12_5173_abrigo_3a5e8ab5-5c48-48f3-98f1-f7c9c5b26ddb_atualizar(iPhone 14 Pro Max)](https://github.com/SOS-RS/frontend/assets/13780312/ff9632bd-1da1-4a76-a1db-f72d9466499f)
![Screenshot from 2024-05-17 13-14-55](https://github.com/SOS-RS/frontend/assets/13780312/654ec894-5a30-4a5b-8a30-1b68c6974bd3)
![pocox3](https://github.com/SOS-RS/frontend/assets/13780312/4f12d005-8d5b-488f-baa2-dfa3bf8c4387)

2024-05-17 17:52 UTC, andradeviniicius approved these changes

2024-05-17 17:58 UTC, andradeviniicius requested changes
.

2024-05-17 22:26 UTC, thiagomrvieira approved these changes
Lgtm

2024-05-18 02:32 UTC, lucianomlima approved these changes

2024-05-19 15:21 UTC, allangalera commented
Postei na issue original. Acredito que podemos resolver isso usando apenas css -> https://caniuse.com/viewport-unit-variants

2024-05-19 16:14 UTC, ThesllaDev approved these changes

2024-05-22 15:41 UTC, vinny-silveira reviewed
Analisando bem... Não precisaria nem mesmo o `useEffect` com os listeners, apenas o cálculo do "vh custom" no topo do arquivo fora da "declaração do componente", pois na prática, o usuário não vai redimensionar a página no smartphone. Fiz alguns testes locais aqui e funcionaram normalmente (desktop e mobile), você pode alterar e fazer mais uns testes locais também, quanto menos a necessidade de `useEffect` melhor., resolvido dessa forma mesmo com Tailwind:

```tsx
document.documentElement.style.setProperty('--vh', `${window.innerHeight * 0.01}px`);

const UpdateShelter = () => {
// ...

  return (
    <div className="flex flex-col items-center h-[calc(var(--vh,1vh)*100)] md:h-screen">

// ...
```

Para telas maiores que 768 (md), pega o vh completo, abaixo disso, ele calcula.

2024-05-22 18:24 UTC, vinny-silveira commented
> Postei na issue original. Acredito que podemos resolver isso usando apenas css -> https://caniuse.com/viewport-unit-variants

Bem mais simples mesmo essa abordagem @allangalera, 92.34% dos browsers e versões já suportam essa unidade:

![image](https://github.com/SOS-RS/frontend/assets/13592890/25536429-1c00-479a-9269-6ff1864ad596)

@felipemrvieira, como temos um suporte para mais de 90%, considere o uso do dvh por gentileza.

2024-05-22 19:37 UTC, felipemrvieira commented
> > Postei na issue original. Acredito que podemos resolver isso usando apenas css -> https://caniuse.com/viewport-unit-variants
> 
> Bem mais simples mesmo essa abordagem @allangalera, 92.34% dos browsers e versões já suportam essa unidade:
> 
> ![image](https://private-user-images.githubusercontent.com/13592890/332915820-25536429-1c00-479a-9269-6ff1864ad596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MDY4NzEsIm5iZiI6MTcxNjQwNjU3MSwicGF0aCI6Ii8xMzU5Mjg5MC8zMzI5MTU4MjAtMjU1MzY0MjktMWMwMC00NzlhLTkyNjktNmZmMTg2NGFkNTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE5MzYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YTQ2NzNiYzA3MmM0NjhlZjUwZGVmMjhhOGQ1OTE3NTg2NjMxMWMwYjRjMDQ1MzM5MTBlMWQyMDY3YmE1YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k-xpT2DVPhiblkqcnRQJWJp7o_A6PV-YM4st3N013EY)
> 
> @felipemrvieira, como temos um suporte para mais de 90%, considere o uso do dvh por gentileza.

Acabei de atualizar o PR. Valeu pelo feedback!

2024-05-23 12:48 UTC, vinny-silveira approved these changes
Por essa abordagem tem uma nível de compatibilidade bem maior que o `dvh`, uma vez que ele calcula a propriedade apenas no "primeiro load" da aplicação e usa a unidade `px`, PR apto ao merge.

2024-05-23 12:49 UTC, vinny-silveira commented
@SOS-RS/frontenders Preciso de mais um review aqui.

2024-06-02 00:24 UTC, larissapissurno approved these changes

2024-06-02 11:48 UTC, felipemrvieira commented
Acredito que está pronto para merge @vinny-silveira @andradeviniicius @larissapissurno

2024-06-02 16:50 UTC, merged

2024-06-02 16:50 UTC, larissapissurno commented
mergeado @felipemrvieira