Update - Melhoria na listagem de suplementos
SOS-RS/frontend pull request #249
Opened 2024-05-18 19:51 UTC by xlucaix

### Melhorar a descoberta de que existem mais itens depois que o limite de 10 é excedido no card

Acesse o card atráves do [Link](https://sosriograndedosul.notion.site/bba977635382411d95adafd32d95417f?v=d7a5ab7c82064286b8b312ad2d32b0a6&p=d208cae935fd4d9899a094dad55c46d9&pm=s)

#### Resumo: 
Eu sou doador. Eu estou tentando entender em profundidade todos os itens que um abrigo específico precisa. Mas não sabia que são inúmeros itens porque pela listagem tive a impressão de que eram só 10 o que faz com que eu não tenha dimensão da verdadeira demanda.

Screenshot da melhoria:
![Screenshot 2024-05-18 at 16 49 55](https://github.com/SOS-RS/frontend/assets/166631000/6931376b-8e89-4514-9660-803259a0df20)

2024-05-18 22:51 UTC, lucianomlima reviewed
Se só está exibindo 10, como o slice e o ajuste que você fez para exibir quantos tem além vai funcionar? Pelo que entendi, essa variável tags sempre vai ter no máximo 10.

2024-05-20 12:07 UTC, xlucaix commented
@lucianomlima Fiz um MR pro back também removendo essa limitação de 10 items, visto que o objetivo é quando exceder mais de 10 items, deverá existir um décimo primeiro 'Chip' com a quantidade restante que não foi exibida. 

Link do PR: 
https://github.com/SOS-RS/backend/pull/136

2024-05-20 14:25 UTC, lucianomlima commented
> @lucianomlima Fiz um PR pro back também removendo essa limitação de 10 items, visto que o objetivo é quando exceder mais de 10 items, deverá existir um décimo primeiro 'Chip' com a quantidade restante que não foi exibida. 
> 
> Link do PR: 
> https://github.com/SOS-RS/backend/pull/136
> 

Deixa isso explícito na descrição do PR, assim quem está revisando sabe que houve alteração lá e quem vai fazer merge sabe que precisa antes que o PR do backend seja aprovado.

2024-05-20 14:26 UTC, lucianomlima approved these changes

2024-05-20 21:31 UTC, xlucaix commented
> > @lucianomlima Fiz um PR pro back também removendo essa limitação de 10 items, visto que o objetivo é quando exceder mais de 10 items, deverá existir um décimo primeiro 'Chip' com a quantidade restante que não foi exibida.
> > Link do PR:
> > [SOS-RS/backend#136](https://github.com/SOS-RS/backend/pull/136)
> 
> Deixa isso explícito na descrição do PR, assim quem está revisando sabe que houve alteração lá e quem vai fazer merge sabe que precisa antes que o PR do backend seja aprovado.

Boa! brigadão mano, vou add lá na descrição do PR pra ficar mais fácil

2024-05-21 14:46 UTC, larissapissurno commented on src/pages/Home/components/ShelterSupplyCategoryRow/ShelterSupplyCategoryRow.tsx
> +            label={`+${tags.length - 10} items`}
podemos trocar `items` por `itens` aqui? pra seguir o padrão de linguagem em PT

2024-05-21 14:49 UTC, vinny-silveira requested changes
O nome correto da class é `text-black-600`, conforme a [documentação oficial disponível aqui](https://tailwindcss.com/docs/text-color) com os tokens de cores. Outro ponto, o bg não está sendo aplicado corretamente:

![image](https://github.com/SOS-RS/frontend/assets/13592890/e850f392-2391-4b50-897d-664b31ca9343)

Sugiro a criação de uma "variante" do chip, com o nome de "moreInfo", adicionando as classes que você precisa, algo assim:

```tsx
moreInfo: 'bg-gray-200 text-black-600'
```

E o chip seria chamado dessa forma: 

```tsx
        {tags.length > 10 && (
          <Chip
            label={`+${tags.length - 10} items`}
            variant='moreInfo'
          />
        )}
```

Aí então teríamos o resultado esperado:

![image](https://github.com/SOS-RS/frontend/assets/13592890/01b73e04-b056-41f6-8fa2-03719711905d)

2024-05-21 14:55 UTC, vinny-silveira commented on src/pages/Home/components/ShelterSupplyCategoryRow/ShelterSupplyCategoryRow.tsx
> +            label={`+${tags.length - 10} items`}
Bom ponto @larissapissurno, inclusive é dessa forma que está no Figma:

![image](https://github.com/SOS-RS/frontend/assets/13592890/98dadd36-b189-44bb-b490-bf9393f25ab2)

Pode ajustar pra nós @xlucaix? Valeu!

2024-05-21 15:19 UTC, larissapissurno commented on src/pages/Home/components/ShelterSupplyCategoryRow/ShelterSupplyCategoryRow.tsx
> +            label={`+${tags.length - 10} items`}
notei tbm que o background está um pouco mais claro no figma @xlucaix , podemos deixar um `bg-gray-200` talvez?

2024-05-22 23:53 UTC, LucasJCM-coder requested changes

2024-05-22 23:53 UTC, LucasJCM-coder commented on src/pages/Home/components/ShelterSupplyCategoryRow/ShelterSupplyCategoryRow.tsx
> +          <Chip label={`+${tags.length - 10} itens`} variant="moreInfo" />
"Notei que quando há exatamente 11 tags, o rótulo do chip exibe `+1 itens`. Para melhorar a precisão e clareza, sugiro que tratemos esse caso específico para exibir `+1 item` em vez de `+1 itens`

2024-05-23 00:25 UTC, xlucaix commented on src/pages/Home/components/ShelterSupplyCategoryRow/ShelterSupplyCategoryRow.tsx
> +          <Chip label={`+${tags.length - 10} itens`} variant="moreInfo" />
Perfeito, vou realizar a alteração

2024-05-23 00:34 UTC, LucasJCM-coder approved these changes

2024-05-23 03:41 UTC, vinny-silveira requested changes
Está faltando o caractere "+" antes do número de itens:

![Screenshot_20240523-004109_Chrome.png](https://github.com/SOS-RS/frontend/assets/13592890/f4e016b6-5a22-4c87-ae7a-9022543a6dc6)

Ajustar, por gentileza.

2024-05-23 12:24 UTC, vinny-silveira approved these changes
PR apto ao merge

2024-05-23 12:26 UTC, vinny-silveira commented
@SOS-RS/frontenders , preciso de mais um review aqui.

2024-05-23 12:40 UTC, lucianomlima approved these changes
✅

2024-05-24 01:05 UTC, larissapissurno approved these changes

2024-05-26 06:22 UTC, LucasJCM-coder approved these changes

2024-05-26 07:04 UTC, merged