Feat 254 melhoria adicao itens
SOS-RS/frontend pull request #275
Opened 2024-05-20 03:03 UTC by larissapissurno

2024-05-20 19:12 UTC, giggio commented
@larissapissurno terminou? Podemos revisar?

2024-05-20 20:04 UTC, larissapissurno commented
oi @giggio, sim, liberado pra revisão

2024-05-21 13:34 UTC, vinny-silveira commented
Olá! @larissapissurno, rodei local aqui e não vi problemas ou comportamentos estranhos, da parte de codificação está bacana também, mas o build não passa por conta de um import que não está mais em uso:

![image](https://github.com/SOS-RS/frontend/assets/13592890/20b9f0ca-f0f6-435d-b771-0b9863d778dc)

Pode ajustar pra gente?

2024-05-21 13:49 UTC, vinny-silveira requested changes
Técnicamente falando, o único problema que impede o merge é o import não usado que é validado durante a build, ajustando este ponto, estaria apto para merge.

2024-05-21 13:55 UTC, larissapissurno commented
oi @vinny-silveira, claro, vou arrumar aqui

2024-05-21 13:57 UTC, larissapissurno commented
@vinny-silveira feito ✅

2024-05-21 13:59 UTC, vinny-silveira approved these changes
Apto ao merge.

2024-05-21 14:02 UTC, merged