feat: add PetsRs link to shelter card
SOS-RS/frontend pull request #302
Opened 2024-05-24 02:35 UTC by coelhotatiane

**OBJETIVO DO PR**
Adição de uma nova feat. [Task aberta aqui](https://github.com/orgs/SOS-RS/projects/1?pane=issue&itemId=63437428)

**O QUE CONSTA NO PR**

- [x] Cada abrigo de pet deve ter um link visível que redirecione para a página correspondente no site Pets RS.
_Observações: não há um id mútuo entre os dois bancos (sos vs pets rs). A busca pelo abrigo correspondente na API de destino está sendo realizada utilizando o nome do abrigo da seguinte forma:_
_1. O nome do abrigo aberto pelo usuário é selecionado;_
_2. Grande parte dos abrigos possui algum separador no nome com algum comentário que não faz parte do nome. Exemplo: "Escola Estadual Infante Dom Henrique [exclusivo Pets]". Por conta disso, tudo que vier depois de separadores como (, -, [ e { será ignorado. Neste caso, a busca será feita considerando "Escola Estadual Infante Dom Henrique"._
_Há possíveis melhorias, mas esse é um start para deixar a busca pelo abrigo pet correspondente mais eficiente._
_3. Se o abrigo pet correspondente for encontrado, o link correspondente é criado. Do contrário, a url fallback será a url geral do Pets Rs._
- [x] O link deve ser claramente identificado e fácil de clicar.
- [x] O link deve abrir a página do abrigo de pets em uma nova aba.
- [x] A URL do link deve ser gerada dinamicamente com base nos dados do abrigo de pet.
- [x] Garantir que o link esteja disponível apenas para abrigos de pets.

**EVIDÊNCIAS DA ALTERAÇÃO**
![image](https://github.com/SOS-RS/frontend/assets/53581377/9cf44f58-6a1f-48a8-b535-4273547f9a97)

![image](https://github.com/SOS-RS/frontend/assets/53581377/1ec8cb86-3f77-4f42-a183-7cfc08b68509)

2024-05-24 13:39 UTC, evertonpavan approved these changes

2024-05-24 14:43 UTC, rhuam commented
@coelhotatiane acho que você pode simplificar bastante sua lógica se incluir uma coluna na tabela shelters chamada, por exemplo, "petsrs_id", se preenchida, ela exibe o link para o site pets rs. O que acha?

2024-05-24 23:52 UTC, coelhotatiane commented
@rhuam então, acho que simplificaria no front sim, mas o back ainda teria que ter essa lógica + algum job recorrente pra adicionar e atualizar os dados no banco. Além disso, os dados dessa forma poderiam não estar tão atualizados quanto estão agora (fazendo a chamada diretamente).

Pela simplicidade optei por deixar no front.. mas se preferir trocar me avisa

2024-05-28 13:40 UTC, luizsonego approved these changes

2024-05-30 14:51 UTC, larissapissurno requested changes
parabéns pelo trabalho @coelhotatiane 🚀 

rodei seu código localmente e está funcionando belezinha, mas acho que podemos melhorar um pouco a estilização se seguirmos a sugestão da @barbiebrega [aqui](https://github.com/SOS-RS/frontend/issues/272#issuecomment-2121496155) pra deixar o link mais evidente, o que acha? 

ps: estou avaliando primeiro a funcionalidade, após o ajuste avaliarei o código 🤝

2024-06-03 22:19 UTC, coelhotatiane commented
> parabéns pelo trabalho @coelhotatiane 🚀
> 
> rodei seu código localmente e está funcionando belezinha, mas acho que podemos melhorar um pouco a estilização se seguirmos a sugestão da @barbiebrega [aqui](https://github.com/SOS-RS/frontend/issues/272#issuecomment-2121496155) pra deixar o link mais evidente, o que acha?
> 
> ps: estou avaliando primeiro a funcionalidade, após o ajuste avaliarei o código 🤝

Done!
![image](https://github.com/SOS-RS/frontend/assets/53581377/79daa17a-bcdf-4c91-8db9-15273eb46512)

2024-06-04 13:32 UTC, larissapissurno approved these changes
LGTM 🚀 ! só deixei um último minor comment, mas no geral parece bom!

2024-06-04 13:32 UTC, larissapissurno commented on src/components/CardAboutShelter/utils.ts
> +}
podemos simplificar um pouco aqui utilizando .replace com regex

`input.replace(/[\(\-\[\{].*$/, '')`

2024-06-04 16:01 UTC, coelhotatiane commented on src/components/CardAboutShelter/utils.ts
> +}
Boa! Comitado. Obrigada!

2024-06-05 15:58 UTC, merged